# Generated by Django 5.0.4 on 2024-04-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='aluno',
        ),
    ]
