# Generated by Django 5.0.4 on 2024-04-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacao", "0004_alter_aluno_nome_completo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="nome_completo",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
