# Generated by Django 5.0.4 on 2024-04-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_alter_aluno_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
