# Generated by Django 5.0.4 on 2024-04-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0009_alter_aluno_nome_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome_completo',
        ),
    ]
